### PR TITLE
Update CM_Ultimate.CT

### PR DESCRIPTION
**Pull request by mrhey12**
I changed game name to "000001B5-Combat Master" because its looking like this in Mac.

### CODE REVIEW

**Comment by InternetNinjo** [comment]
@mrhey12 you do realize this is a public change? changing that would break the script for windows users as the executable for windows is .exe

**Comment by mrhey12** [comment]
İs it possible to make a Mac version?

1 Kas 2024 Cum 11:19 tarihinde ✿𝙸𝚗𝚝𝚎𝚛𝚗𝚎𝚝𝙽𝚒𝚗𝚓𝚊♡ <
***@***.***> şunu yazdı:

**Comment by InternetNinjo** [comment]
Cheat engine doesn't exist for mac.


________________________________

**Comment by ZoDDeL** [comment]
this table only supports windows.
cheat engine for mac is a thing ( https://cheatengine.org/download/mac/CheatEngine752.app.zip )
but i dont use a mac / OSX so there is no chance.
you can just fork and modify to your needs.

**Pull request closed without merging**
